export interface ExportOrderRow {
  orderId: string;
  customerName: string;
  status: string;
  pickupDate: string;
  pickupTime: string;
  createdAt: string;
  paymentType: string;
  total: number;
  itemSummary: string;
}

export interface ExportSummary {
  totalOrders: number;
  activeOrders: number;
  completedOrders: number;
  declinedOrders: number;
  totalRevenue: number;
  averageOrderValue: number;
}

export interface ReportExportPayload {
  reportType: string;
  generatedBy: string;
  generatedAt: string;
  dateFrom: string;
  dateTo: string;
  summary: ExportSummary;
  orders: ExportOrderRow[];
}

const escapeCsv = (value: string | number) => {
  const text = String(value ?? "");
  if (/[",\n]/.test(text)) {
    return `"${text.replace(/"/g, "\"\"")}"`;
  }
  return text;
};

const formatMoney = (value: number) =>
  Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const sanitizeFilePart = (value: string) =>
  value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const buildReportFilename = (payload: ReportExportPayload, extension: string) => {
  const type = sanitizeFilePart(payload.reportType || "report");
  const from = sanitizeFilePart(payload.dateFrom || "na");
  const to = sanitizeFilePart(payload.dateTo || "na");
  return `cake-with-joy-${type}-${from}-to-${to}.${extension}`;
};

export const downloadReportCsv = (payload: ReportExportPayload) => {
  const lines = [
    ["Cake with Joy Report"],
    ["Report Type", payload.reportType],
    ["Generated By", payload.generatedBy],
    ["Generated At", payload.generatedAt],
    ["Date From", payload.dateFrom],
    ["Date To", payload.dateTo],
    [],
    ["Summary"],
    ["Total Orders", payload.summary.totalOrders],
    ["Active Orders", payload.summary.activeOrders],
    ["Completed Orders", payload.summary.completedOrders],
    ["Declined Orders", payload.summary.declinedOrders],
    ["Total Revenue", formatMoney(payload.summary.totalRevenue)],
    ["Average Order Value", formatMoney(payload.summary.averageOrderValue)],
    [],
    ["Orders"],
    ["Order ID", "Customer", "Status", "Pickup Date", "Pickup Time", "Created At", "Payment Type", "Total", "Items"],
    ...payload.orders.map((order) => [
      order.orderId,
      order.customerName,
      order.status,
      order.pickupDate,
      order.pickupTime,
      order.createdAt,
      order.paymentType,
      formatMoney(order.total),
      order.itemSummary,
    ]),
  ];

  const csv = lines.map((row) => row.map((cell) => escapeCsv(cell ?? "")).join(",")).join("\n");
  downloadBlob(new Blob([csv], { type: "text/csv;charset=utf-8;" }), buildReportFilename(payload, "csv"));
};

export const downloadReportExcel = (payload: ReportExportPayload) => {
  const rows = payload.orders
    .map(
      (order) => `
        <tr>
          <td>${order.orderId}</td>
          <td>${order.customerName}</td>
          <td>${order.status}</td>
          <td>${order.pickupDate}</td>
          <td>${order.pickupTime}</td>
          <td>${order.createdAt}</td>
          <td>${order.paymentType}</td>
          <td>${formatMoney(order.total)}</td>
          <td>${order.itemSummary}</td>
        </tr>`
    )
    .join("");

  const html = `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: Arial, sans-serif; padding: 24px; }
          table { border-collapse: collapse; width: 100%; margin-top: 12px; }
          th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
          th { background: #f8d7eb; }
          h1, h2 { margin-bottom: 8px; }
        </style>
      </head>
      <body>
        <h1>Cake with Joy Report</h1>
        <p><strong>Report Type:</strong> ${payload.reportType}</p>
        <p><strong>Generated By:</strong> ${payload.generatedBy}</p>
        <p><strong>Generated At:</strong> ${payload.generatedAt}</p>
        <p><strong>Date Range:</strong> ${payload.dateFrom} to ${payload.dateTo}</p>
        <h2>Summary</h2>
        <table>
          <tr><th>Total Orders</th><th>Active Orders</th><th>Completed Orders</th><th>Declined Orders</th><th>Total Revenue</th><th>Average Order Value</th></tr>
          <tr>
            <td>${payload.summary.totalOrders}</td>
            <td>${payload.summary.activeOrders}</td>
            <td>${payload.summary.completedOrders}</td>
            <td>${payload.summary.declinedOrders}</td>
            <td>${formatMoney(payload.summary.totalRevenue)}</td>
            <td>${formatMoney(payload.summary.averageOrderValue)}</td>
          </tr>
        </table>
        <h2>Orders</h2>
        <table>
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Customer</th>
              <th>Status</th>
              <th>Pickup Date</th>
              <th>Pickup Time</th>
              <th>Created At</th>
              <th>Payment Type</th>
              <th>Total</th>
              <th>Items</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </body>
    </html>`;

  downloadBlob(
    new Blob([html], { type: "application/vnd.ms-excel;charset=utf-8;" }),
    buildReportFilename(payload, "xls")
  );
};

